# Generated by Django 5.0 on 2024-08-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_selected",
        ),
        migrations.AddField(
            model_name="project",
            name="Building_rera_license",
            field=models.FileField(
                blank=True, null=True, upload_to="construction_files/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="building_license_no",
            field=models.FileField(
                blank=True, null=True, upload_to="construction_files/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="construction_area",
            field=models.FileField(
                blank=True, null=True, upload_to="construction_files/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="location_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="pincode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="place",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_brocher",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AddField(
            model_name="project",
            name="project_photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="social_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="webside",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
