# Generated by Django 5.0 on 2024-08-13 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0008_alter_customuser_user_type"),
        ("projects", "0003_project_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_user",
                to="boq.clientinfo",
            ),
        ),
    ]
