# Generated by Django 5.0 on 2024-09-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_brocher",
            field=models.FileField(
                blank=True, null=True, upload_to="construction_files/"
            ),
        ),
    ]
