# Generated by Django 5.0 on 2024-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_project_brocher"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_photo",
            new_name="interior_project_photo",
        ),
        migrations.AddField(
            model_name="project",
            name="exterior_project_photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos"),
        ),
    ]
