# Generated by Django 5.0 on 2024-11-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_project_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="documents",
            field=models.FileField(
                blank=True, null=True, upload_to="construction_files/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="drawings",
            field=models.FileField(
                blank=True, null=True, upload_to="construction_files/"
            ),
        ),
    ]
