# Generated by Django 5.0 on 2024-08-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_contract_margins_contract_margin_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
