# Generated by Django 5.0 on 2024-08-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_brand_website"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brand",
            old_name="website",
            new_name="website_url",
        ),
    ]
