# Generated by Django 5.0 on 2024-08-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_rename_website_brand_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="unit_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
