# Generated by Django 5.0 on 2024-08-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_unit_description_unit_unit_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialgroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialgroup",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="material_logos/"),
        ),
    ]
