# Generated by Django 5.0 on 2024-08-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_materialgroup_description_materialgroup_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="material",
            name="gst_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="materialgroup",
            name="sub_groups",
            field=models.ManyToManyField(
                blank=True, related_name="materials", to="materials.subgroup"
            ),
        ),
    ]
