# Generated by Django 5.0 on 2024-08-20 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_subgroup_material_gst_value_material_sale_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material_product",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials_product_group",
                to="materials.materialgroup",
            ),
        ),
    ]
