# Generated by Django 5.0 on 2024-08-20 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_alter_material_product_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material_product",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials_name",
                to="materials.material",
            ),
        ),
    ]
