# Generated by Django 5.0 on 2024-08-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0010_alter_material_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract_margin_product",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Contract_Margins",
                to="materials.contract_margins",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_brand",
                to="materials.brand",
            ),
        ),
    ]
