# Generated by Django 5.0 on 2024-08-23 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0014_contract_margin_product_formula"),
        ("projects", "0004_alter_project_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Total_Contract_Margin_product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_me", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField()),
                (
                    "formula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_contract_product_formula",
                        to="materials.formula",
                    ),
                ),
                (
                    "gst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_Contract_Margins_product_gst",
                        to="materials.gst",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_Contract_Margins",
                        to="materials.contract_margins",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_projects_Contract_Margin",
                        to="projects.project",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_Contract_Margins_product_unit",
                        to="materials.unit",
                    ),
                ),
            ],
        ),
    ]
