# Generated by Django 5.0 on 2024-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0016_total_operational_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="total_operational_cost",
            name="name",
        ),
        migrations.AddField(
            model_name="total_operational_cost",
            name="expense_name",
            field=models.CharField(default="ON & OFF-SITE EXPENSE", max_length=255),
        ),
    ]
