# Generated by Django 5.0 on 2024-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0018_material_subgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
