# Generated by Django 5.0 on 2024-09-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0019_workgroup_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gst",
            name="rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
