# Generated by Django 5.0 on 2024-09-30 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0020_alter_gst_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessSubGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="businesstype",
            name="businesssubgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_subgroup",
                to="materials.businesssubgroup",
            ),
        ),
    ]
