# Generated by Django 5.0 on 2024-09-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0021_businesssubgroup_businesstype_businesssubgroup"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businesstype",
            old_name="businesssubgroup",
            new_name="businessubgroup",
        ),
    ]
