# Generated by Django 5.0 on 2024-09-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0022_rename_businesssubgroup_businesstype_businessubgroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businesstype",
            name="businessubgroup",
        ),
        migrations.AddField(
            model_name="businesstype",
            name="business_sub_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="business_sub_group",
                to="materials.businesssubgroup",
            ),
        ),
    ]
