# Generated by Django 5.1.1 on 2024-10-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_remove_businesstype_businessubgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='engineer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
