# Generated by Django 5.1.1 on 2024-10-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_unit_engineer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='engineer',
        ),
        migrations.AddField(
            model_name='unit',
            name='engineer_field',
            field=models.BooleanField(default=False),
        ),
    ]
