# Generated by Django 5.1.1 on 2024-10-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_remove_unit_engineer_unit_engineer_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroupSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='workgroup',
            name='workgroup_sub_groups',
            field=models.ManyToManyField(blank=True, related_name='workgroup_sub_group', to='materials.workgroupsubgroup'),
        ),
    ]
