# Generated by Django 5.1.1 on 2024-10-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_workgroupsubgroup_workgroup_workgroup_sub_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='workgroup_sub_groups',
        ),
        migrations.DeleteModel(
            name='WorkGroupSubGroup',
        ),
    ]
