# Generated by Django 5.1.1 on 2024-10-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_remove_workgroup_workgroup_sub_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodesgroupSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='workgroup',
            name='codesgroup_sub_groups',
            field=models.ManyToManyField(blank=True, related_name='codesgroup_sub_group', to='materials.codesgroupsubgroup'),
        ),
    ]
