# Generated by Django 5.0 on 2024-10-15 13:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0028_codesgroupsubgroup_workgroup_codesgroup_sub_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialgroup",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workgroup",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
