# Generated by Django 5.0 on 2024-10-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0029_alter_materialgroup_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
