# Generated by Django 5.0 on 2024-10-15 14:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0030_alter_unit_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
