# Generated by Django 5.0 on 2024-10-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0031_alter_unit_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="operational_cost_product",
            name="formula",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operational_product_formula",
                to="materials.formula",
            ),
        ),
    ]
