# Generated by Django 5.0 on 2024-08-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0001_initial"),
        ("materials", "0003_contract_margins_contract_margin_product_and_more"),
        ("projects", "0002_remove_project_is_selected_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("free_code", models.CharField(blank=True, max_length=50, null=True)),
                ("work_detail", models.TextField(blank=True, null=True)),
                ("basic_rate", models.CharField(blank=True, max_length=20, null=True)),
                ("quantity", models.CharField(blank=True, max_length=50, null=True)),
                ("full_rate", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boq_gst",
                        to="materials.gst",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boq_unit",
                        to="materials.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BOQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basicform_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "basicform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basic_form",
                        to="boq.basicform",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boq_project",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
