# Generated by Django 5.0 on 2024-08-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0002_basicform_boq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="user",
        ),
        migrations.AddField(
            model_name="otp",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
