# Generated by Django 5.0 on 2024-08-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0004_remove_boq_basicform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicform",
            name="table_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contractwork",
            name="table_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="finishing",
            name="table_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="floor",
            name="table_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="wallmasonry",
            name="table_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
