# Generated by Django 5.0 on 2024-08-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0005_basicform_table_name_contractwork_table_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("client", "Client"),
                    ("projectuser", "ProjectUser"),
                ],
                default="provider",
                max_length=20,
                null=True,
            ),
        ),
    ]
