# Generated by Django 5.0 on 2024-08-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0007_clientinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("client", "Client"),
                    ("projectuser", "ProjectUser"),
                ],
                default="projectuser",
                max_length=20,
                null=True,
            ),
        ),
    ]
