# Generated by Django 5.0 on 2024-09-02 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0008_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinfo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
