# Generated by Django 5.0 on 2024-09-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0009_clientinfo_created_by"),
        ("codes", "0004_code_execution_ex_name_code_material_mat_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finishing",
            name="code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finishing_code",
                to="codes.code",
            ),
        ),
        migrations.AlterField(
            model_name="floor",
            name="code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floor_code",
                to="codes.code",
            ),
        ),
        migrations.AlterField(
            model_name="wallmasonry",
            name="code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wall_code",
                to="codes.code",
            ),
        ),
    ]
