# Generated by Django 5.0 on 2024-09-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0011_clientinfo_address_clientinfo_cin_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finishing",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
