# Generated by Django 5.0 on 2024-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0013_remove_wallmasonry_basic_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractform",
            name="table_heading_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contractwork",
            name="table_heading_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="finishing",
            name="table_heading_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="floor",
            name="table_heading_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="wallmasonry",
            name="table_heading_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
