# Generated by Django 5.0 on 2024-09-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0014_abstractform_table_heading_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="finishing",
            old_name="code",
            new_name="free_code",
        ),
    ]
