# Generated by Django 5.0 on 2024-09-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0017_clientbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinfo",
            name="social_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
