# Generated by Django 5.1.2 on 2024-10-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0019_abstractform_table_order_contractwork_table_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='boq_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
