# Generated by Django 5.0 on 2024-10-30 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0020_boq_boq_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="boq",
            name="basic_amount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="boq",
            name="gst_amount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="boq",
            name="gst_applied",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="ReportForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_name", models.CharField(blank=True, max_length=50, null=True)),
                ("table_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "table_heading_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("table_order", models.PositiveIntegerField(default=0)),
                (
                    "gst_to_be_paid",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("gst_refund", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gst_to_be_collected",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gst_to_be_paid_per",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "gst_refund_per",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "total_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gst_to_be_collected_per",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "boq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_form",
                        to="boq.boq",
                    ),
                ),
            ],
        ),
    ]
