# Generated by Django 5.0 on 2024-11-06 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0021_boq_basic_amount_boq_gst_amount_boq_gst_applied_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientbook",
            name="client",
        ),
        migrations.RemoveField(
            model_name="clientbook",
            name="client_info",
        ),
        migrations.RemoveField(
            model_name="clientbook",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="clientinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="clientinfo",
            constraint=models.UniqueConstraint(
                fields=("created_by", "user"), name="unique_client_per_creator"
            ),
        ),
        migrations.DeleteModel(
            name="ClientBook",
        ),
    ]
