# Generated by Django 5.0 on 2024-08-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("role_description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_type",
            field=models.CharField(
                choices=[
                    ("jobseeker", "Job Seeker"),
                    ("business", "Business"),
                    ("client", "Client"),
                ],
                default="jobseeker",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobprofile",
            name="experience",
            field=models.ManyToManyField(
                blank=True, related_name="experience", to="profile.experience"
            ),
        ),
    ]
