# Generated by Django 5.0 on 2024-08-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_experience_profile_profile_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="short_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
