# Generated by Django 5.0 on 2024-08-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_profile_short_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="short_link",
        ),
        migrations.AddField(
            model_name="profile",
            name="unique_id",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
