# Generated by Django 5.0 on 2024-08-12 07:50

import profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0004_remove_profile_short_link_profile_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="project_brochures",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=profile.models.get_project_brochure_path,
            ),
        ),
        migrations.AlterField(
            model_name="jobprofile",
            name="medical_report",
            field=models.FileField(
                blank=True, null=True, upload_to=profile.models.get_medical_report_path
            ),
        ),
        migrations.AlterField(
            model_name="jobprofile",
            name="passport_type_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=profile.models.get_passport_photo_path
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=profile.models.get_profile_photo_path
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="project_brochures",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=profile.models.get_project_brochure_path,
            ),
        ),
    ]
