# Generated by Django 5.0 on 2024-08-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_alter_businessprofile_project_brochures_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Socials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fb", "Facebook"),
                            ("insta", "Instagram"),
                            ("whatsapp", "WhatsApp"),
                            ("x", "X"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("snapchat", "Snapchat"),
                            ("telegram", "Telegram"),
                            ("other", "Other"),
                        ],
                        null=True,
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="social_link_additional",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_link_additional",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="website",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="website",
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="social_link",
            field=models.ManyToManyField(
                blank=True, related_name="business_social_link", to="profile.socials"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_link",
            field=models.ManyToManyField(
                blank=True, related_name="profile_social_link", to="profile.socials"
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="website",
            field=models.ManyToManyField(
                blank=True, related_name="business_websites", to="profile.website"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.ManyToManyField(
                blank=True, related_name="profile_websites", to="profile.website"
            ),
        ),
    ]
