# Generated by Django 5.0 on 2024-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0006_socials_website_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="address",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="google_plus_code",
            field=models.CharField(blank=True, null=True),
        ),
    ]
