# Generated by Django 5.0 on 2024-08-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0007_businessprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="email",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="phone",
            field=models.CharField(blank=True, null=True),
        ),
    ]
