# Generated by Django 5.0 on 2024-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0008_businessprofile_email_businessprofile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socials",
            name="link",
            field=models.CharField(blank=True, null=True),
        ),
    ]
