# Generated by Django 5.0 on 2024-08-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0009_alter_socials_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobprofile",
            name="short_work_history",
            field=models.CharField(blank=True, null=True),
        ),
    ]
