# Generated by Django 5.0 on 2024-08-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0010_jobprofile_short_work_history"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
