# Generated by Django 5.0 on 2024-08-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0012_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("jobseeker", "Job Seeker"),
                    ("business", "Business"),
                    ("client", "Client"),
                ],
                default="jobseeker",
                max_length=20,
                null=True,
            ),
        ),
    ]
