# Generated by Django 5.0 on 2024-09-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0015_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobprofile",
            name="adhar_no",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
