# Generated by Django 5.0 on 2024-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0016_alter_jobprofile_adhar_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="phone",
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, null=True),
        ),
    ]
