# Generated by Django 5.0 on 2024-09-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0017_remove_businessprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobprofile",
            name="looking_for_international",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="jobprofile",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Single"),
                    ("M", "Married"),
                    ("P", "Partnered"),
                    ("W", "Widowed"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
