# Generated by Django 5.0 on 2024-09-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0018_alter_jobprofile_looking_for_international_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobprofile",
            old_name="accident_policy_valid_upto",
            new_name="insurance_policy_valid_upto",
        ),
        migrations.AddField(
            model_name="jobprofile",
            name="insurance_company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
