# Generated by Django 5.0 on 2024-09-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile",
            "0019_rename_accident_policy_valid_upto_jobprofile_insurance_policy_valid_upto_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobprofile",
            name="vehicle_insurance_company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
