# Generated by Django 5.0 on 2024-09-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0020_jobprofile_vehicle_insurance_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="scale",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
