# Generated by Django 5.0 on 2024-09-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0021_businessprofile_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="company_size",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
