# Generated by Django 5.0 on 2024-11-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0022_businessprofile_company_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="business_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobprofile",
            name="business_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
