# Generated by Django 5.0 on 2024-09-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0002_groupname"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupName",
        ),
    ]
