# Generated by Django 5.1.1 on 2024-10-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_delete_groupname'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroupSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='industry',
            name='workgroup_sub_groups',
            field=models.ManyToManyField(blank=True, related_name='workgroup_sub_group', to='administrator.workgroupsubgroup'),
        ),
    ]
