# Generated by Django 5.0 on 2024-10-15 13:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0004_workgroupsubgroup_industry_workgroup_sub_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industry",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
