# Generated by Django 5.0 on 2024-08-20 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0002_remove_code_execution_code_remove_code_material_code_and_more"),
        ("execution", "0005_alter_execution_product_group_and_more"),
        ("materials", "0009_alter_material_product_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="code_execution",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution_code_group",
                to="execution.executiongroup",
            ),
        ),
        migrations.AddField(
            model_name="code_material",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_code_group",
                to="materials.materialgroup",
            ),
        ),
        migrations.AlterField(
            model_name="code_execution",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_execution_unit",
                to="materials.unit",
            ),
        ),
        migrations.AlterField(
            model_name="code_material",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_material_unit",
                to="materials.unit",
            ),
        ),
    ]
