# Generated by Django 5.0 on 2024-08-20 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0003_code_execution_group_code_material_group_and_more"),
        ("execution", "0005_alter_execution_product_group_and_more"),
        ("materials", "0010_alter_material_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="code_execution",
            name="ex_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_execution_name",
                to="execution.execution",
            ),
        ),
        migrations.AddField(
            model_name="code_material",
            name="mat_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_materials_name",
                to="materials.material",
            ),
        ),
    ]
