# Generated by Django 5.0 on 2024-09-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0004_code_execution_ex_name_code_material_mat_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="execution_total_gst",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="code",
            name="material_total_gst",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
