# Generated by Django 5.0 on 2024-09-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0008_code_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="code",
            name="created_by",
        ),
    ]
