# Generated by Django 5.0 on 2024-09-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0009_remove_code_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="code",
            old_name="creator_name",
            new_name="created_by",
        ),
    ]
