# Generated by Django 5.0 on 2024-10-10 12:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0011_code_creator_name_alter_code_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="note",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
