# Generated by Django 5.0 on 2024-10-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0012_alter_code_note"),
        ("materials", "0028_codesgroupsubgroup_workgroup_codesgroup_sub_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="gst_per",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="code",
            name="operational_cost_basicvalue",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="code",
            name="operational_cost_subtotal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="code",
            name="operational_cost_totalrate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="code_execution",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="code_material",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="code_offsiteexpense",
            name="formula",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offsideexpense_formula",
                to="materials.formula",
            ),
        ),
        migrations.AddField(
            model_name="code_offsiteexpense",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="code_onsiteexpense",
            name="formula",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onsideexpense_formula",
                to="materials.formula",
            ),
        ),
        migrations.AddField(
            model_name="code_onsiteexpense",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
