# Generated by Django 5.0 on 2024-10-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0013_code_gst_per_code_operational_cost_basicvalue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="margin_total_gst",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="code",
            name="operational_cost_gst",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
