# Generated by Django 5.0 on 2024-10-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0014_code_margin_total_gst_code_operational_cost_gst"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="margin_total_gst_value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="code",
            name="operational_cost_gst_value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
