# Generated by Django 5.0 on 2024-10-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0015_code_margin_total_gst_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
