# Generated by Django 5.0 on 2024-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codes", "0017_code_subgroup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="code_offsiteexpense",
            name="description",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="code_onsiteexpense",
            name="description",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
