# Generated by Django 5.0 on 2024-08-05 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0001_initial"),
        ("materials", "0003_contract_margins_contract_margin_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="execution_product",
            name="brand",
        ),
        migrations.AddField(
            model_name="execution_product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="execution_product",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution",
                to="execution.executiongroup",
            ),
        ),
        migrations.AddField(
            model_name="execution_product",
            name="gst_value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="execution_product",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="execution_product",
            name="gst",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ex_gst",
                to="materials.gst",
            ),
        ),
        migrations.AlterField(
            model_name="execution_product",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ex_unit",
                to="materials.unit",
            ),
        ),
        migrations.AlterField(
            model_name="executiongroup",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_group",
                        to="execution.executiongroup",
                    ),
                ),
                (
                    "gst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_gst",
                        to="materials.gst",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_unit",
                        to="materials.unit",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="execution_product",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution",
                to="execution.execution",
            ),
        ),
    ]
