# Generated by Django 5.0 on 2024-08-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0002_remove_execution_product_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="executiongroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="executiongroup",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="execution_logos/"
            ),
        ),
    ]
