# Generated by Django 5.0 on 2024-08-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0003_executiongroup_description_executiongroup_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="gst_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="execution",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
