# Generated by Django 5.0 on 2024-08-20 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0004_execution_gst_value_execution_sale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execution_product",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution_product_group",
                to="execution.executiongroup",
            ),
        ),
        migrations.AlterField(
            model_name="execution_product",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution_product_name",
                to="execution.execution",
            ),
        ),
    ]
