# Generated by Django 5.0 on 2024-10-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0005_alter_execution_product_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionSubGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="execution",
            name="sub_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="execution_subgroup",
                to="execution.executionsubgroup",
            ),
        ),
    ]
