# Generated by Django 5.0 on 2024-10-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0006_executionsubgroup_execution_sub_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="execution",
            name="sub_groups",
        ),
        migrations.AddField(
            model_name="executiongroup",
            name="sub_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="execution_subgroup",
                to="execution.executionsubgroup",
            ),
        ),
    ]
