# Generated by Django 5.0 on 2024-10-04 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0007_remove_execution_sub_groups_and_more"),
        ("materials", "0023_remove_businesstype_businessubgroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="subgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subgroup_execution",
                to="materials.subgroup",
            ),
        ),
    ]
