# Generated by Django 5.0 on 2024-10-11 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0008_execution_subgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execution",
            name="subgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subgroup_execution",
                to="execution.executionsubgroup",
            ),
        ),
    ]
