# Generated by Django 5.0 on 2024-10-15 13:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0009_alter_execution_subgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execution",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="executiongroup",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
